# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - slack-bluesky-unfurl

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'
          include-prerelease: true

      - name: Build with dotnet
        working-directory: ./SlackBskyUnfurl
        run: dotnet build --configuration Release

      # - name: Install dotnet ef tool
      #   shell: bash
      #   run: dotnet tool install --global dotnet-ef

      # - name: Install dotnet ef tool
      #   if: ${{ inputs.dotnet-ef-version != '' }}
      #   shell: bash
      #   env:
      #     VERSION: ${{ inputs.dotnet-ef-version }}
      #   run: dotnet tool install --global dotnet-ef --version $VERSION

      # - name: Update database
      #   shell: bash
      #   env:
      #     PROJECT_PATH: ${{ inputs.project-path }}
      #     STARTUP_PROJECT_PATH: ${{ inputs.startup-project-path }}
      #     CONTEXT: ${{ inputs.context }}
      #     CONNECTION: ${{ inputs.connection }}
      #   run: |
      #     export PATH=$PATH:$HOME/.dotnet/tools
      #     . ~/.bashrc
      #     dotnet tool restore
      #     dotnet ef database update --verbose --project=$PROJECT_PATH --startup-project=$STARTUP_PROJECT_PATH --context $CONTEXT --connection $CONNECTION

      - name: Warren - .NET Migrations
        uses: warrenbrasil/dotnet-migrations@v3
        with:
          project-path: ./SlackBskyUnfurl
          startup-project-path: ./SlackBskyUnfurl
          dotnet-ef-version: ''
          context: SlackBskyContext
          connection: ${{ secrets.SQL_CONNECTION_STRING }}

      - name: update database
        working-directory: ./SlackBskyUnfurl
        run: dotnet ef database update --project SlackBskyUnfurl --startup-project SlackBskyUnfurl

      - name: dotnet publish
        working-directory: ./SlackBskyUnfurl
        run: dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/slack-bsky-unfurl

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/slack-bsky-unfurl

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: .net-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'slack-bluesky-unfurl'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D33CFD8F85294B8C8D8C4386BEC4DF0A }}
          package: .
